---
# tasks file for install nodejs

# install nodejs

# do add public key
- name: add nodejs apt key
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

# do add repo
- name: add nodejs repository
  become: true
  apt_repository:
    repo: deb https://deb.nodesource.com/node_20.x {{ ansible_distribution_release }} main
    state: present
    update_cache: true

# install nodejs
- name: install nodejs
  become: true
  apt:
    name: nodejs
    update-cache: true
  changed_when: 0

