---
# tasks file for install mariaDB

# do install mariaDB

- name: MariaDB | install
  ignore_errors: yes
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - mariadb-server
    - mariadb-client
    - python3-pymysql

# set password
- name: Sets the root password
  ignore_errors: yes
  mysql_user:
    name: root
    password: "{{ mysql_root_password }}"
    login_user: root
    login_unix_socket: /var/run/mysqld/mysqld.sock

