---
# tasks file for start yarn

# Increasing the amount of inotify watchers
- ansible.posix.sysctl:
    name: fs.inotify.max_user_watches
    value: '524288'
    state: present

# upgrade yarn packages
- name: build frontend project
  become: true
  yarn:
    path: /opt/src/frontend


# init oc service
- name: init oc service
  file:
    src: /opt/scripts/oc_service.sh
    dest: /usr/bin/oc
    state: link

# start frontend
- name: oc start_frontend
  become: true
  command: oc start_frontend
  async: 2592000               # 60*60*24*30 – 1 month
  poll: 0
